"""
The one-click sample workspace, the pipeline-progress endpoint, and the
product-facing provider status.

Three things are pinned here, and all three are about the same failure:
showing a person something the backend did not actually establish.

  * `POST /runs/sample` must ingest the sample folder through the same
    path an upload takes. The way this goes wrong quietly is by
    shortcutting it — writing a source row with a hardcoded type, or
    quietly confirming a file the classifier was unsure about so the
    demo does not have to ask. So the sample's classification is
    asserted to equal what an upload of the same bytes produces, and
    nothing is asserted about *which* provider any file is: the folder
    is regenerated independently of this code, and a test that pins its
    contents would be pinning a snapshot rather than the behaviour.

  * `GET /runs/{id}/progress` must report where a run actually got to. A
    progress display is the easiest place in a product to put a number
    nobody computed, so the counts are checked against the records
    themselves, and a count that is not yet knowable is checked to be
    `null` rather than a zero that would render as a measurement.

  * `GET /ai/status` must never carry key material, and must say `null`
    rather than invent a "last successful request" it never observed.

Offline throughout: `ACCORD_AI_DISABLED=1`, so every outcome here is a
property of this code rather than of a network.
"""

from __future__ import annotations

import os
import sys
import time
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

import pytest
from fastapi.testclient import TestClient

from app.api import ai as ai_api
from app.api import runs as runs_api
from app.ledger import db


@pytest.fixture()
def client(tmp_path, monkeypatch):
    monkeypatch.setenv("ACCORD_AI_DISABLED", "1")
    monkeypatch.setattr(db, "DB_PATH", tmp_path / "sample_workspace.db")
    db._local.__dict__.clear()
    db.init_db()
    ai_api._reset_cache_for_tests()
    from app.main import app
    with TestClient(app) as c:
        yield c
    ai_api._reset_cache_for_tests()
    db._local.__dict__.clear()


# The order the pipeline can legally move through. Used to assert that
# what a poller observes never goes backwards; DETERMINISTIC and
# INVESTIGATING are the same pass named for what it is currently doing,
# and it can only gain AI consultations, never lose them.
STAGE_ORDER = {
    "INSPECTING": 0, "NORMALISING": 1, "DETERMINISTIC": 2,
    "INVESTIGATING": 3, "REVIEW": 4, "COMPLETE": 5,
}


def workspace_files() -> list[Path]:
    return runs_api.sample_workspace_files()


def confirm_everything(client, run_id) -> None:
    """Answer the classifier's questions the way a person would.

    Confirms the type it already proposed — the point is that it asked,
    not that the answer differs.
    """
    sources = client.get(f"/runs/{run_id}").json()["sources"]
    updates = [
        {"source_id": s["source_id"], "source_type": s["source_type"],
         "role": s["role"], "confirmed": True}
        for s in sources
        if (s["detection"].get("classification") or {}).get("needs_confirmation")
    ]
    if updates:
        response = client.put(f"/runs/{run_id}/plan", json={"sources": updates, "confirmed": True})
        assert response.status_code == 200, response.text


def ambiguous_workspace(tmp_path) -> Path:
    """A two-file workspace with exactly one record that needs the semantic tier.

    ORD-9001's settlement carries a different reference and differently
    worded narration, so exact matching cannot resolve it and there is
    not enough corroborating evidence to settle it deterministically.
    The other two match on their references and never reach the tier —
    they are there so the run is a reconciliation rather than a single
    edge case.

    Built here rather than taken from the sample folder because the
    sample folder is generated by another script and this test is about
    a property of the pipeline, not of that data.
    """
    workspace = tmp_path / "ambiguity_workspace"
    workspace.mkdir()
    (workspace / "orders_shopify_export.csv").write_text(
        "order_id,order_date,amount,currency,customer_name,description\n"
        "ORD-9001,2026-03-05,1250.00,INR,Acme Traders,Acme Traders order 9001\n"
        "ORD-9002,2026-03-06,2310.50,INR,Bluewave Labs,Bluewave Labs order 9002\n"
        "ORD-9003,2026-03-07,4415.75,INR,Cobalt Foods,Cobalt Foods order 9003\n"
    )
    (workspace / "razorpay_settlements_mar.csv").write_text(
        "payment_id,settlement_id,order_reference,settlement_date,gross_amount,fee,tax,"
        "currency,description,status\n"
        "pay_A1,setl_1,TXN-55501,2026-03-06,1250.00,20.00,3.60,INR,ACME TRADERS PVT LTD payout,processed\n"
        "pay_A2,setl_1,ORD-9002,2026-03-07,2310.50,30.00,5.40,INR,Bluewave Labs order 9002,processed\n"
        "pay_A3,setl_1,ORD-9003,2026-03-08,4415.75,40.00,7.20,INR,Cobalt Foods order 9003,processed\n"
    )
    return workspace


class StubModelVerifier:
    """A verifier that answers as a provider would, without a network.

    `backend` is the string a real chain writes — "provider:model" — so
    the records it produces are indistinguishable, to everything
    downstream, from records a live provider served. That is the point:
    the counting has to be driven by what is stored, not by what the
    process happens to know about its own configuration.
    """

    backend = "gemini:stub-model"

    def compare(self, comparison):
        from app.engine.semantic import SemanticVerdictResult

        return SemanticVerdictResult(
            verdict="AMBIGUOUS", confidence=0.4,
            rationale="stub verifier: deliberately undecided",
            backend=self.backend,
        )


def run_to_completion(client, run_id, timeout=180) -> list[dict]:
    """Poll /progress the way the UI does, keeping every snapshot."""
    seen = []
    deadline = time.time() + timeout
    while time.time() < deadline:
        progress = client.get(f"/runs/{run_id}/progress").json()
        seen.append(progress)
        if progress["complete"]:
            return seen
        time.sleep(0.05)
    raise AssertionError(f"run did not complete in time; last stage {seen[-1]['stage']}")


# ---------------------------------------------------------------------------
# POST /runs/sample
# ---------------------------------------------------------------------------

def test_the_sample_run_loads_every_file_in_the_workspace_folder(client):
    """Every export in the folder becomes a source, counted from disk.

    The folder is generated by a separate script and changes; the
    assertion is therefore against what is on disk at this moment, never
    against a remembered file list or count.
    """
    files = workspace_files()
    assert files, "no sample workspace on disk to test against"

    response = client.post("/runs/sample", json={})
    assert response.status_code == 200, response.text
    body = response.json()

    assert body["errors"] == [], body["errors"]
    assert body["source_count"] == len(files)
    assert {s["filename"] for s in body["sources"]} == {p.name for p in files}
    assert body["record_count"] == sum(s["row_count"] for s in body["sources"])
    assert body["record_count"] > 0

    # The POST /runs shape, so a caller can treat it as a created run.
    assert body["run_id"].startswith("run_")
    assert body["status"] == "DRAFT"
    assert body["label"]

    # And it is a real run in the store, with real sources behind it.
    stored = client.get(f"/runs/{body['run_id']}").json()
    assert len(stored["sources"]) == len(files)
    assert {s["filename"] for s in stored["sources"]} == {p.name for p in files}

    for source in body["sources"]:
        for field in ("detected_source_type", "detection_confidence", "row_count",
                      "needs_confirmation", "duplicate_of", "provider"):
            assert field in source, f"{source['filename']} is missing {field}"
        assert source["row_count"] > 0
        assert 0.0 <= source["detection_confidence"] <= 1.0


def test_sample_classification_equals_an_upload_of_the_same_bytes(client):
    """The sample is ingested, not injected.

    The cheap way to build this endpoint is to write source rows
    directly with a type taken from the filename. That would look
    identical until the day the classifier disagreed with the filename,
    which is exactly the day it matters. So every field the classifier
    produces is compared against the same file uploaded through
    /runs/{id}/sources — no expected values are written down here,
    because the folder's contents are not this test's to know.
    """
    files = workspace_files()
    assert files

    sample = client.post("/runs/sample", json={}).json()
    by_name = {s["filename"]: s for s in sample["sources"]}

    upload_run = client.post("/runs", json={"label": "control"}).json()["run_id"]
    for path in files:
        response = client.post(
            f"/runs/{upload_run}/sources",
            files=[("files", (path.name, path.read_bytes(), "application/octet-stream"))],
        )
        assert response.status_code == 200, response.text
        uploaded = response.json()["sources"][0]
        loaded = by_name[path.name]

        for field in ("detected_source_type", "detection_confidence", "provider",
                      "needs_confirmation", "source_type", "role", "suggested_role"):
            assert loaded[field] == uploaded[field], (
                f"{path.name}: sample reported {field}={loaded[field]!r}, "
                f"an upload of the same bytes reported {uploaded[field]!r}"
            )
        assert loaded["row_count"] == uploaded["detection"]["row_count"]
        assert loaded["role_confirmed"] == uploaded["role_confirmed"]


def test_a_duplicate_file_in_the_sample_is_flagged_exactly_as_an_upload_would_be(client):
    """Byte-identical files are reported, not hidden.

    Only asserted when the folder actually contains a duplicate — the
    folder is not this test's to arrange — but when it does, the second
    copy must point at the first by both id and filename.
    """
    sample = client.post("/runs/sample", json={}).json()
    by_id = {s["source_id"]: s for s in sample["sources"]}
    flagged = [s for s in sample["sources"] if s["duplicate_of"]]

    hashes = {}
    for path in workspace_files():
        import hashlib
        hashes.setdefault(hashlib.sha256(path.read_bytes()).hexdigest(), []).append(path.name)
    repeated = [names for names in hashes.values() if len(names) > 1]

    assert len(flagged) == sum(len(names) - 1 for names in repeated)
    for source in flagged:
        original = by_id[source["duplicate_of"]]
        assert source["duplicate_of_filename"] == original["filename"]
        assert source["filename"] != original["filename"]
    assert sample["duplicates"] == [
        {"filename": s["filename"], "duplicate_of_filename": s["duplicate_of_filename"]}
        for s in flagged
    ]


def test_a_sample_source_the_classifier_is_unsure_about_still_asks(client):
    """No auto-confirmation to smooth the demo.

    Whatever the folder holds, the invariant is the same: a source the
    classifier flagged is a source that has not been confirmed, and it
    is exactly the set of sources execution refuses to proceed on.
    """
    sample = client.post("/runs/sample", json={}).json()
    run_id = sample["run_id"]
    unsure = [s for s in sample["sources"] if s["needs_confirmation"]]

    for source in unsure:
        assert source["role_confirmed"] is False, (
            f"{source['filename']} was flagged for confirmation and confirmed anyway"
        )
    assert sample["needs_confirmation"] == [s["filename"] for s in unsure]

    execute = client.post(f"/runs/{run_id}/execute", json={})
    if unsure:
        assert execute.status_code == 400, execute.text
        detail = execute.json()["detail"]
        for source in unsure:
            assert source["filename"] in detail
    else:
        assert execute.status_code == 200, execute.text


def test_an_ambiguous_file_in_the_sample_folder_blocks_execution(client, tmp_path, monkeypatch):
    """The same property, arranged rather than hoped for.

    The previous test asserts an invariant over whatever the real folder
    contains; this one points the endpoint at a folder built to contain
    a file nothing can confidently identify, so the refusal is covered
    even if the real sample data is one day entirely unambiguous.
    """
    workspace = tmp_path / "ambiguous_workspace"
    workspace.mkdir()
    (workspace / "orders.csv").write_text(
        "order_id,order_date,amount,currency,customer\n"
        "ORD-1,2026-03-01,1000.00,INR,Alpha\n"
        "ORD-2,2026-03-02,2000.00,INR,Beta\n"
    )
    # No provider vocabulary, no gateway or bank column names, a filename
    # that says nothing: there is no evidence here to be confident on.
    (workspace / "export.csv").write_text(
        "col_a,col_b,col_c\n"
        "2026-03-01,1000.00,ref-1\n"
        "2026-03-02,2000.00,ref-2\n"
    )
    monkeypatch.setattr(runs_api, "DEMO_WORKSPACE_DIR", workspace)

    sample = client.post("/runs/sample", json={}).json()
    assert sample["source_count"] == 2
    unsure = [s for s in sample["sources"] if s["needs_confirmation"]]
    assert unsure, "a file with no identifying evidence should not be classified confidently"
    assert all(s["role_confirmed"] is False for s in unsure)

    execute = client.post(f"/runs/{sample['run_id']}/execute", json={})
    assert execute.status_code == 400
    assert unsure[0]["filename"] in execute.json()["detail"]


def test_a_missing_sample_workspace_is_a_clean_404(client, tmp_path, monkeypatch):
    monkeypatch.setattr(runs_api, "DEMO_WORKSPACE_DIR", tmp_path / "not_here")
    response = client.post("/runs/sample", json={})
    assert response.status_code == 404
    assert "sample workspace" in response.json()["detail"]


def test_sidecar_files_are_not_ingested_as_exports(client, tmp_path, monkeypatch):
    """A manifest sitting next to the exports is metadata, not a source."""
    workspace = tmp_path / "workspace_with_sidecars"
    workspace.mkdir()
    (workspace / "orders.csv").write_text(
        "order_id,order_date,amount,currency\nORD-1,2026-03-01,1000.00,INR\n"
    )
    (workspace / "_manifest.json").write_text('{"generator": "test"}')
    (workspace / "README.md").write_text("# notes")
    monkeypatch.setattr(runs_api, "DEMO_WORKSPACE_DIR", workspace)

    sample = client.post("/runs/sample", json={}).json()
    assert [s["filename"] for s in sample["sources"]] == ["orders.csv"]
    assert sample["errors"] == []


# ---------------------------------------------------------------------------
# GET /runs/{run_id}/progress
# ---------------------------------------------------------------------------

def test_progress_on_an_unknown_run_is_a_clean_404(client):
    response = client.get("/runs/run_does_not_exist/progress")
    assert response.status_code == 404
    assert response.json()["detail"] == "run not found"


def test_progress_reports_null_for_what_is_not_yet_known(client):
    """A run that has not been executed has not measured anything.

    `null`, not zero. A zero on a progress display is indistinguishable
    from a measurement of nothing, and a reader would be right to treat
    it as one.
    """
    run_id = client.post("/runs", json={"label": "empty"}).json()["run_id"]
    progress = client.get(f"/runs/{run_id}/progress").json()

    assert progress["started"] is False
    assert progress["complete"] is False
    assert progress["total"] is None, "the size of an unexecuted run is not known"
    assert progress["processed"] == 0
    assert progress["error"] is None
    assert progress["updated_at"] is None

    assert progress["semantic_backend"] is None, "nothing has served a tier nothing reached"
    assert progress["semantic_tier_invoked"] == 0
    assert progress["ai_consulted"] == 0

    assert [s["state"] for s in progress["stages"]] == ["PENDING"] * 5
    for stage in progress["stages"]:
        assert stage["count"] is None, f"{stage['key']} reported a count before it ran"
        assert stage["total"] is None, f"{stage['key']} reported a total before it ran"


def test_progress_advances_through_the_real_stages_and_reaches_complete(client):
    """Stage state tracks execution, and never goes backwards."""
    files = workspace_files()
    assert files

    sample = client.post("/runs/sample", json={}).json()
    run_id = sample["run_id"]
    confirm_everything(client, run_id)

    before = client.get(f"/runs/{run_id}/progress").json()
    assert before["stage"] == "INSPECTING" and before["started"] is False

    execute = client.post(f"/runs/{run_id}/execute", json={})
    assert execute.status_code == 200, execute.text
    summary = execute.json()

    snapshots = run_to_completion(client, run_id)
    observed = [p["stage"] for p in snapshots]
    positions = [STAGE_ORDER[s] for s in observed]
    assert positions == sorted(positions), f"progress went backwards: {observed}"
    assert observed[-1] == "COMPLETE"

    # Reading, mapping and normalising happen before /execute returns, so
    # by the first poll they are genuinely finished — and they report the
    # counts the executor actually recorded, not a stand-in.
    final = snapshots[-1]
    stages = {s["key"]: s for s in final["stages"]}
    assert [s["state"] for s in final["stages"]] == ["DONE"] * 5

    assert stages["INSPECTING"]["count"] == len(files)
    assert stages["INSPECTING"]["total"] == len(files)
    assert stages["NORMALISING"]["count"] == (
        summary["ledger_records"] + summary["settlement_records"]
    )
    assert stages["DETERMINISTIC"]["total"] == summary["total_records"]
    assert stages["DETERMINISTIC"]["count"] == summary["total_records"]

    assert final["processed"] == final["total"] == summary["total_records"]
    assert final["complete"] is True
    assert final["error"] is None

    # Every stage that advanced during the run reported a count from the
    # store, so the panel can never show a step that "ran" with nothing
    # behind it.
    assert stages["INVESTIGATING"]["count"] == final["ai_consulted"]
    assert stages["REVIEW"]["count"] == final["unresolved"]


def test_progress_counts_agree_with_the_records_they_describe(client):
    """ai_consulted and unresolved are counted, not asserted."""
    sample = client.post("/runs/sample", json={}).json()
    run_id = sample["run_id"]
    confirm_everything(client, run_id)
    assert client.post(f"/runs/{run_id}/execute", json={}).status_code == 200
    final = run_to_completion(client, run_id)[-1]

    records = client.get(f"/batch/{run_id}/records?limit=100000").json()
    assert len(records) == final["total"]
    assert final["unresolved"] == sum(1 for r in records if r["outcome"] == "HUMAN_REVIEW")

    def served_by_a_model(record):
        backend = (record["ai_backend"] or "").lower()
        return bool(record["ai_invoked"] and backend and "heuristic" not in backend)

    assert final["semantic_tier_invoked"] == sum(1 for r in records if r["ai_invoked"])
    assert final["ai_consulted"] == sum(1 for r in records if served_by_a_model(r))
    assert final["heuristic_consulted"] == sum(
        1 for r in records if r["ai_invoked"] and "heuristic" in (r["ai_backend"] or "").lower()
    )
    assert final["ai_consulted"] <= final["semantic_tier_invoked"]
    assert final["stage"] == "COMPLETE"


def test_the_deciding_headline_names_what_the_pass_is_actually_doing(client):
    """DETERMINISTIC and INVESTIGATING are one pass, named honestly.

    The engine consults the model *inside* the matching loop, on the
    record whose evidence turned out to be ambiguous — there is no
    separate investigation phase to report. So the headline says
    INVESTIGATING only once a consultation has actually happened on this
    run, and both rows advance together rather than one after the other.

    Driven by rewinding the stored phase to the one the executor writes
    while the loop is running, because a finished offline run is over
    before a poller can see the middle of it.
    """
    from app.ledger import store

    sample = client.post("/runs/sample", json={}).json()
    run_id = sample["run_id"]
    confirm_everything(client, run_id)
    assert client.post(f"/runs/{run_id}/execute", json={}).status_code == 200
    final = run_to_completion(client, run_id)[-1]

    store.update_run_progress(run_id, phase=runs_api.PHASE_DECIDING)
    # The batch row is the authority on completion, so it has to be moved
    # back too or the recorded phase is correctly overruled.
    store.get_conn().execute("UPDATE batches SET status='RUNNING' WHERE batch_id=?", (run_id,))

    mid = client.get(f"/runs/{run_id}/progress").json()
    if final["ai_consulted"] > 0:
        assert mid["stage"] == "INVESTIGATING" and mid["ai_consulted"] > 0
    else:
        assert mid["stage"] == "DETERMINISTIC", (
            "nothing was investigated, so the headline must not claim it was"
        )
    states = {s["key"]: s["state"] for s in mid["stages"]}
    assert states["DETERMINISTIC"] == states["INVESTIGATING"] == "ACTIVE", (
        "matching and investigation are interleaved; neither finishes before the other starts"
    )
    assert states["REVIEW"] == "ACTIVE"
    assert states["INSPECTING"] == states["NORMALISING"] == "DONE"


def test_progress_survives_a_restarted_process(client):
    """A refresh mid-run must not lose where the run got to.

    Simulated by clearing the process's connection state — the endpoint
    has nothing in memory to fall back on, so anything it reports has to
    have come off disk.
    """
    sample = client.post("/runs/sample", json={}).json()
    run_id = sample["run_id"]
    confirm_everything(client, run_id)
    assert client.post(f"/runs/{run_id}/execute", json={}).status_code == 200
    run_to_completion(client, run_id)

    db._local.__dict__.clear()
    reread = client.get(f"/runs/{run_id}/progress").json()
    assert reread["stage"] == "COMPLETE"
    assert reread["complete"] is True
    assert reread["processed"] == reread["total"]
    assert [s["state"] for s in reread["stages"]] == ["DONE"] * 5


def test_progress_reports_a_run_that_refused_to_start(client, tmp_path, monkeypatch):
    """A refusal is recorded, so the run does not look like it is working."""
    workspace = tmp_path / "one_sided"
    workspace.mkdir()
    (workspace / "orders_shopify_export.csv").write_text(
        "order_id,order_date,amount,currency,customer_name\n"
        "ORD-1,2026-03-01,1000.00,INR,Alpha\n"
        "ORD-2,2026-03-02,2000.00,INR,Beta\n"
    )
    monkeypatch.setattr(runs_api, "DEMO_WORKSPACE_DIR", workspace)

    sample = client.post("/runs/sample", json={}).json()
    run_id = sample["run_id"]
    confirm_everything(client, run_id)

    execute = client.post(f"/runs/{run_id}/execute", json={})
    assert execute.status_code == 400
    assert "settlement" in execute.json()["detail"]

    progress = client.get(f"/runs/{run_id}/progress").json()
    assert progress["error"] == execute.json()["detail"]
    assert progress["complete"] is False


def test_a_dataset_batch_still_reports_progress_it_can_prove(client):
    """`/batch/run` does not go through the run executor at all.

    It records no phase, so progress has to be derived from the batch
    row alone — and must still be truthful rather than empty.
    """
    batch = client.post("/batch/run", json={"dataset": "dev", "limit": 5}).json()
    batch_id = batch["batch_id"]

    deadline = time.time() + 120
    while time.time() < deadline:
        progress = client.get(f"/runs/{batch_id}/progress").json()
        if progress["complete"]:
            break
        assert STAGE_ORDER[progress["stage"]] >= STAGE_ORDER["DETERMINISTIC"]
        time.sleep(0.05)
    else:
        raise AssertionError("dataset batch did not complete in time")

    assert progress["stage"] == "COMPLETE"
    assert progress["processed"] == progress["total"] == batch["total_records"]
    # It has no sources, so it never inspected any, and says so.
    inspecting = progress["stages"][0]
    assert inspecting["count"] is None and inspecting["total"] is None


def _finish(client, run_id) -> dict:
    confirm_everything(client, run_id)
    response = client.post(f"/runs/{run_id}/execute", json={})
    assert response.status_code == 200, response.text
    return run_to_completion(client, run_id)[-1]


def test_an_offline_run_never_claims_a_model_was_consulted(client, tmp_path, monkeypatch):
    """The regression this whole split exists to prevent.

    `ai_invoked` on a record means "the semantic tier was reached". With
    no provider configured, the offline heuristic serves that tier — and
    a summary that reads "AI consulted: 1" off that column would be
    telling a viewer a model was used when none was called. The tier
    total is still reported, under a name that says what it is.
    """
    monkeypatch.setattr(runs_api, "DEMO_WORKSPACE_DIR", ambiguous_workspace(tmp_path))
    run_id = client.post("/runs/sample", json={}).json()["run_id"]
    final = _finish(client, run_id)

    assert final["semantic_tier_invoked"] > 0, "the fixture must reach the semantic tier"
    assert final["ai_consulted"] == 0, "no provider was called, so nothing was consulted"
    assert final["heuristic_consulted"] == final["semantic_tier_invoked"]
    assert final["semantic_backend"] == "heuristic"

    records = client.get(f"/batch/{run_id}/records?limit=1000").json()
    invoked = [r for r in records if r["ai_invoked"]]
    assert invoked and all("heuristic" in (r["ai_backend"] or "") for r in invoked)

    investigating = {s["key"]: s for s in final["stages"]}["INVESTIGATING"]
    assert investigating["count"] == 0
    assert "no model was called" in investigating["detail"]
    assert str(final["semantic_tier_invoked"]) in investigating["detail"]

    # And the headline must never have promoted this run to INVESTIGATING.
    from app.ledger import store
    store.update_run_progress(run_id, phase=runs_api.PHASE_DECIDING)
    store.get_conn().execute("UPDATE batches SET status='RUNNING' WHERE batch_id=?", (run_id,))
    assert client.get(f"/runs/{run_id}/progress").json()["stage"] == "DETERMINISTIC"


def test_a_model_backed_run_reports_the_consultations_it_actually_made(client, tmp_path, monkeypatch):
    """The other half: a real provider answering must be counted.

    The verifier is stubbed rather than mocked out of the path — it
    stamps the same "provider:model" backend a live chain writes, so the
    counting is exercised end to end against stored rows, offline.
    """
    monkeypatch.setattr(runs_api, "DEMO_WORKSPACE_DIR", ambiguous_workspace(tmp_path))
    monkeypatch.setattr(runs_api, "get_semantic_verifier", lambda: StubModelVerifier())

    run_id = client.post("/runs/sample", json={}).json()["run_id"]
    final = _finish(client, run_id)

    assert final["semantic_tier_invoked"] > 0
    assert final["ai_consulted"] == final["semantic_tier_invoked"]
    assert final["heuristic_consulted"] == 0
    assert final["semantic_backend"] == "model"

    records = client.get(f"/batch/{run_id}/records?limit=1000").json()
    assert [r["ai_backend"] for r in records if r["ai_invoked"]] == [
        StubModelVerifier.backend
    ] * final["ai_consulted"]

    investigating = {s["key"]: s for s in final["stages"]}["INVESTIGATING"]
    assert investigating["count"] == final["ai_consulted"]
    assert "consult the model" in investigating["detail"]
    assert "no model was called" not in investigating["detail"]

    from app.ledger import store
    store.update_run_progress(run_id, phase=runs_api.PHASE_DECIDING)
    store.get_conn().execute("UPDATE batches SET status='RUNNING' WHERE batch_id=?", (run_id,))
    assert client.get(f"/runs/{run_id}/progress").json()["stage"] == "INVESTIGATING"


def test_a_run_that_reached_no_ambiguity_says_so_rather_than_nothing(client, tmp_path, monkeypatch):
    """Zero consultations is a result, and it is reported as one."""
    workspace = tmp_path / "unambiguous"
    workspace.mkdir()
    (workspace / "orders_shopify_export.csv").write_text(
        "order_id,order_date,amount,currency,customer_name\n"
        "ORD-1,2026-03-05,1250.00,INR,Acme Traders\n"
        "ORD-2,2026-03-06,2310.50,INR,Bluewave Labs\n"
    )
    (workspace / "razorpay_settlements_mar.csv").write_text(
        "payment_id,settlement_id,order_reference,settlement_date,gross_amount,fee,tax,"
        "currency,description,status\n"
        "pay_1,setl_1,ORD-1,2026-03-06,1250.00,20.00,3.60,INR,Acme Traders,processed\n"
        "pay_2,setl_1,ORD-2,2026-03-07,2310.50,30.00,5.40,INR,Bluewave Labs,processed\n"
    )
    monkeypatch.setattr(runs_api, "DEMO_WORKSPACE_DIR", workspace)

    final = _finish(client, client.post("/runs/sample", json={}).json()["run_id"])
    assert final["semantic_tier_invoked"] == 0
    assert final["ai_consulted"] == 0
    assert final["semantic_backend"] is None
    investigating = {s["key"]: s for s in final["stages"]}["INVESTIGATING"]
    assert investigating["detail"] == "No record needed more than deterministic evidence."


def test_a_heuristic_run_is_not_evidence_that_a_provider_is_reachable(client, tmp_path, monkeypatch):
    """The offline verifier must never register as a provider success.

    /ai/status reads the newest decision each provider served. A run the
    heuristic served writes `ai_backend` too, and counting it there would
    put a `last_success` timestamp against a provider nobody called.
    """
    from app.ledger import store

    monkeypatch.setattr(runs_api, "DEMO_WORKSPACE_DIR", ambiguous_workspace(tmp_path))
    final = _finish(client, client.post("/runs/sample", json={}).json()["run_id"])
    assert final["heuristic_consulted"] > 0

    assert store.last_semantic_success_by_provider() == {}
    body = client.get("/ai/status").json()
    assert body["primary"]["last_success"] is None
    assert body["fallback"]["last_success"] is None


# ---------------------------------------------------------------------------
# GET /ai/status
# ---------------------------------------------------------------------------

def test_ai_status_reports_the_chain_without_a_last_success_it_never_saw(client):
    """Offline, nothing has succeeded, so there is no timestamp to give."""
    response = client.get("/ai/status")
    assert response.status_code == 200
    body = response.json()

    assert body["status"] in ("AI_AVAILABLE", "AI_FALLBACK_ACTIVE", "AI_UNAVAILABLE")
    for side in ("primary", "fallback"):
        assert set(body[side]) >= {"name", "available", "last_success"}
        assert isinstance(body[side]["name"], str) and body[side]["name"]
        assert isinstance(body[side]["available"], bool)
        assert body[side]["last_success"] is None, (
            f"{side} reported a successful request that never happened"
        )
    assert body["primary"]["name"] != body["fallback"]["name"]


def test_ai_status_carries_no_key_material_and_no_model_ids(client, monkeypatch):
    """Nothing on this surface has been near a credential.

    The keys are set to recognisable values first: a status endpoint that
    happens to be safe because the environment is empty is not a test of
    anything.
    """
    monkeypatch.setenv("GEMINI_API_KEY", "AIzaTESTKEYSHOULDNEVERAPPEAR0000000000")
    monkeypatch.setenv("GROQ_API_KEY", "gsk_TESTKEYSHOULDNEVERAPPEAR00000000000")
    monkeypatch.setenv("GEMINI_MODEL", "gemini-model-should-never-appear")
    ai_api._reset_cache_for_tests()

    raw = client.get("/ai/status").text
    assert "AIzaTESTKEYSHOULDNEVERAPPEAR0000000000" not in raw
    assert "gsk_TESTKEYSHOULDNEVERAPPEAR00000000000" not in raw
    assert "gemini-model-should-never-appear" not in raw
    for env_name, value in os.environ.items():
        if any(t in env_name.upper() for t in ("KEY", "SECRET", "TOKEN", "PASSWORD")):
            if value and len(value) >= 8:
                assert value not in raw, f"{env_name} leaked into /ai/status"

    body = client.get("/ai/status").json()
    assert "model" not in body["primary"] and "model" not in body["fallback"]
    assert "providers" not in body


def test_ai_health_is_unchanged_by_the_status_endpoint(client):
    """The diagnostic view keeps its own shape; /ai/status is additive."""
    health = client.get("/ai/health").json()
    assert set(health) >= {"status", "providers", "checked_at", "detail"}
    assert isinstance(health["providers"], list)
    assert client.get("/api/ai/health").status_code == 200
    assert client.get("/api/ai/status").status_code == 200
